/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

function triangle(n) {
  return (n*(n+1))/2;
}

function isPentagonal(n) {
  /* 
  (n*(3*n-1)) = 2*a
  3*n^2 - n = 2*a
  3*n^2 - n - 2*a = 0
  1 +- sqrt(1+4*3*2) / 2*3
  */
  // Bhaskara 
  var aux = Math.sqrt(1+(24*n));
  var sol = (1 + aux) / 6; // The other solution gives negative
  return (sol==Math.floor(sol));
}

function isHexagonal(n) {
  /* 
  (n*(2*n-1)) = a
  2*n^2 - n = a
  2*n^2 - n - a = 0
  1 +- sqrt(1+4*2*1) / 2*2
  */
  // Bhaskara 
  var aux = Math.sqrt(1+(8*n));
  var sol = (1 + aux) / 4; // The other solution gives negative
  return (sol==Math.floor(sol));
}


for (var i=285+1; true; i++) {
  var n = triangle(i);
  if (isPentagonal(n) && isHexagonal(n)) { 
    console.log(n);
	break;
  }
}

// 1533776805
