/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

var suma = 0;
var ultimo = 2;
var penultimo = 1;
var aux = 0;
while (ultimo < 4000000) { 
  if (ultimo%2==0) {suma+=ultimo}; 
  aux = ultimo; 
  ultimo += penultimo; 
  penultimo = aux;
}
console.log(suma);

// Output: 4613732
